package sim

import (
	"encoding/json"
	"os"
	"reflect"
	"sort"
	"testing"
)

// Expected decisions are generated by scripts/research_sim/vllm_native_oracle.py
// from the unmodified pinned Python decision body. This store scripts resources,
// not scheduling. A deferred simulator allocation maps to native async admission.
type nativeFixtureStore struct {
	KVStore
	failures, prefixes, loads, restored map[string]int64
	blocked                             map[string]bool
}

func (*nativeFixtureStore) PreservesOutputHistory() bool { return true }
func (*nativeFixtureStore) ReleaseKVBlocks(*Request)     {}
func (s *nativeFixtureStore) AllocateKVBlocks(r *Request, _, _ int64, _ []int64) bool {
	if n := s.failures[r.ID]; n != 0 {
		if n > 0 {
			s.failures[r.ID]--
		}
		return false
	}
	if n := s.loads[r.ID]; n > 0 {
		s.restored[r.ID] = n
		s.blocked[r.ID] = true
		delete(s.loads, r.ID)
		return false
	}
	return true
}
func (s *nativeFixtureStore) GetRequestCachedPrefix(r *Request) CachedPrefix {
	return CachedPrefix{Tokens: max(s.prefixes[r.ID], s.restored[r.ID])}
}
func (s *nativeFixtureStore) PollDeferred(int64) []string {
	ids := []string{}
	for id := range s.blocked {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}
func (s *nativeFixtureStore) IsDeferred(id string) bool { return s.blocked[id] }
func (*nativeFixtureStore) ClearDeferred(string)        {}

type nativeRequestSpec struct {
	ID                        string
	Prompt, Computed, Emitted int64
}
type nativeStepSpec struct {
	Complete, Blocked         []string
	Arrivals                  []nativeRequestSpec
	Prefixes, Loads, Failures map[string]int64
}
type nativeSnapshot struct {
	Grants, Computed, Emitted            map[string]int64
	Running, Waiting, Skipped, Preempted []string
}
type nativeCase struct {
	Name                      string
	Budget, Chunk             int64
	MaxSeqs                   int64 `json:"max_seqs"`
	MaxModelLen               int64 `json:"max_model_len"`
	Running, Waiting, Skipped []nativeRequestSpec
	Steps                     []nativeStepSpec
	Expected                  []nativeSnapshot
}

func TestVLLMNativePinnedSourceParity(t *testing.T) {
	data, err := os.ReadFile("testdata/vllm_native.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		Revision string
		Cases    []nativeCase
	}
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if fixture.Revision != VLLMNativeRevision || len(fixture.Cases) < 20 {
		t.Fatal("missing native reference cases")
	}
	for _, c := range fixture.Cases {
		t.Run(c.Name, func(t *testing.T) {
			v := NewVLLMNativeBatchFormation()
			store := &nativeFixtureStore{restored: map[string]int64{}}
			ctx := BatchContext{RunningBatch: &Batch{}, WaitQ: &WaitQueue{}, KVCache: store,
				MaxNumBatchedTokens: c.Budget, PrefillTokenThreshold: c.Chunk, MaxNumSeqs: c.MaxSeqs,
				MaxModelLen: c.MaxModelLen, ComputedTokens: map[string]int64{}}
			if ctx.MaxNumSeqs == 0 {
				ctx.MaxNumSeqs = 8
			}
			requests := map[string]*Request{}
			add := func(spec nativeRequestSpec, group string) {
				r := &Request{ID: spec.ID, InputTokens: make([]TokenID, spec.Prompt),
					OutputTokens: make([]TokenID, 100), ProgressIndex: spec.Computed,
					TTFTSet: spec.Emitted > 0, preservedOutputTokens: spec.Emitted, State: StateQueued}
				requests[r.ID] = r
				if group == "running" {
					r.State = StateRunning
					ctx.RunningBatch.Requests = append(ctx.RunningBatch.Requests, r)
					ctx.ComputedTokens[r.ID] = r.ProgressIndex
				} else {
					r.ProgressIndex = 0 // pending native load counters are backend state
					ctx.WaitQ.Enqueue(r)
					if group == "skipped" {
						v.skipped = append(v.skipped, r.ID)
						store.restored[r.ID] = spec.Computed
					}
				}
			}
			for _, r := range c.Running {
				add(r, "running")
			}
			for _, r := range c.Waiting {
				add(r, "waiting")
			}
			for _, r := range c.Skipped {
				add(r, "skipped")
			}
			for i, step := range c.Steps {
				for _, id := range step.Complete {
					for j, r := range ctx.RunningBatch.Requests {
						if r.ID == id {
							ctx.RunningBatch.Requests = append(ctx.RunningBatch.Requests[:j], ctx.RunningBatch.Requests[j+1:]...)
							break
						}
					}
				}
				for _, r := range step.Arrivals {
					add(r, "waiting")
				}
				store.failures, store.prefixes, store.loads = step.Failures, step.Prefixes, step.Loads
				store.blocked = map[string]bool{}
				for _, id := range step.Blocked {
					store.blocked[id] = true
				}
				ctx.StepCount = i
				result := v.FormBatch(ctx)
				ctx.RunningBatch = result.RunningBatch
				got := nativeSnapshot{Grants: map[string]int64{}, Computed: map[string]int64{}, Emitted: map[string]int64{},
					Running: []string{}, Waiting: []string{}, Skipped: append([]string{}, v.skipped...), Preempted: []string{}}
				for _, r := range result.RunningBatch.Requests {
					got.Running = append(got.Running, r.ID)
					got.Computed[r.ID] = ctx.ComputedTokens[r.ID]
					if r.NumNewTokens > 0 {
						got.Grants[r.ID] = int64(r.NumNewTokens)
					}
				}
				for _, r := range ctx.WaitQ.Items() {
					got.Waiting = append(got.Waiting, r.ID)
				}
				for _, p := range result.Preempted {
					got.Preempted = append(got.Preempted, p.Request.ID)
				}
				sort.Strings(got.Preempted)
				for id, r := range requests {
					got.Emitted[id] = r.EmittedTokens()
				}
				if !reflect.DeepEqual(got, c.Expected[i]) {
					a, _ := json.Marshal(got)
					b, _ := json.Marshal(c.Expected[i])
					t.Fatalf("round %d\ngot  %s\nwant %s", i, a, b)
				}
				for _, r := range ctx.RunningBatch.Requests {
					if r.NumNewTokens > 0 {
						end := max(r.PrefillEnd(), r.InputLen()+r.EmittedTokens())
						r.ProgressIndex = ctx.ComputedTokens[r.ID]
						if r.ProgressIndex == end {
							r.TTFTSet = true
						}
					}
				}
			}
		})
	}
}

func TestVLLMNativeIgnoresFutureOutputLengthAndContents(t *testing.T) {
	for _, n := range []int{0, 1, 1000} {
		r := &Request{ID: "r", InputTokens: make([]TokenID, 4), ProgressIndex: 4, TTFTSet: true, OutputTokens: make([]TokenID, n)}
		ctx := BatchContext{RunningBatch: &Batch{Requests: []*Request{r}}, WaitQ: &WaitQueue{},
			KVCache: &nativeFixtureStore{}, MaxNumBatchedTokens: 8, MaxNumSeqs: 1, ComputedTokens: map[string]int64{"r": 4}}
		NewVLLMNativeBatchFormation().FormBatch(ctx)
		if r.NumNewTokens != 1 {
			t.Fatal("future output affected decode grant", n, r.NumNewTokens)
		}
	}
}
